//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Optimization;
using System.Web.Routing;
using MVC;

public class _Page_Views_AdminVuelos_Create_cshtml : System.Web.Mvc.WebViewPage<Models.Productos> {
private static object @__o;
#line hidden
public _Page_Views_AdminVuelos_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
private void @__RazorDesignTimeHelpers__() {
#pragma warning disable 219

#line 1 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       Models.Productos __inheritsHelper = null;


#line default
#line hidden
#pragma warning restore 219
}
public override void Execute() {

#line 2 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
  
    ViewBag.Title = "Agregar Productos";


#line default
#line hidden

#line 3 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
using (Html.BeginForm())
{
    

#line default
#line hidden

#line 4 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
                            


#line default
#line hidden

#line 6 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
__o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
   __o = Html.LabelFor(model => model.Codigo, htmlAttributes: new
        {
            @class =
        "control-label col-md-2"
        });


#line default
#line hidden

#line 8 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.EditorFor(model => model.Codigo, new
            {
                htmlAttributes = new
                {
                    @class =
            "form-control"
                }
            });


#line default
#line hidden

#line 9 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.Codigo, "", new
            {
                @class =
            "text-danger"
            });


#line default
#line hidden

#line 10 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.LabelFor(model => model.Nombre, htmlAttributes: new
            {
                @class =
            "control-label col-md-2"
            });


#line default
#line hidden

#line 11 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
           __o = Html.EditorFor(model => model.Nombre, new
                {
                    htmlAttributes = new
                    {
                        @class =
                "form-control"
                    }
                });


#line default
#line hidden

#line 12 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.Nombre, "", new
                {
                    @class =
                "text-danger"
                });


#line default
#line hidden

#line 13 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
   __o = Html.LabelFor(model => model.Descripcion, htmlAttributes: new
        {
            @class =
        "control-label col-md-2"
        });


#line default
#line hidden

#line 14 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.EditorFor(model => model.Descripcion, new
            {
                htmlAttributes = new
                {
            @type = "date",
                    @class = "form-control"
                }
            });


#line default
#line hidden

#line 15 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.Descripcion, "", new
            {
                @class =
            "text-danger"
            });


#line default
#line hidden

#line 16 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
   __o = Html.LabelFor(model => model.Cantidad, htmlAttributes: new
        {
            @class =
        "control-label col-md-2"
        });


#line default
#line hidden

#line 17 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.EditorFor(model => model.Cantidad, new
            {
                htmlAttributes = new
                {
            @type = "date",
                    @class = "form-control"
                }
            });


#line default
#line hidden

#line 18 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.Cantidad, "", new
            {
                @class =
            "text-danger"
            });


#line default
#line hidden

#line 19 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
   __o = Html.LabelFor(model => model.Precio, htmlAttributes: new
        {
            @class =
        "control-label col-md-2"
        });


#line default
#line hidden

#line 20 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.EditorFor(model => model.Precio, new
            {
                htmlAttributes = new
                {
            @type = "date",
                    @class = "form-control"
                }
            });


#line default
#line hidden

#line 21 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.Precio, "", new
            {
                @class =
            "text-danger"
            });


#line default
#line hidden

#line 22 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
   __o = Html.LabelFor(model => model.CategoriaID, htmlAttributes: new
        {
            @class =
        "control-label col-md-2"
        });


#line default
#line hidden

#line 23 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.EditorFor(model => model.CategoriaID, new
            {
                htmlAttributes = new
                {
            @type = "date",
                    @class = "form-control"
                }
            });


#line default
#line hidden

#line 24 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
       __o = Html.ValidationMessageFor(model => model.CategoriaID, "", new
            {
                @class =
            "text-danger"
            });


#line default
#line hidden

#line 25 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
      
}

#line default
#line hidden

#line 26 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
__o = Html.ActionLink("Volver a Productos", "Index");


#line default
#line hidden
DefineSection("Scripts", () => {


#line 27 "C:\Users\Usuario\source\repos\Proyecto-Grupo6\MVC\Views\AdminVuelos\Create.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
