//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Productos_BuscarNombre_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Productos_BuscarNombre_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\JMP\AppData\Local\Temp\B7433C29BA00A6DA12FD93255137B6D8E567\9\Proyecto-Grupo6\MVC\Views\Productos\BuscarNombre.cshtml"
  
    ViewBag.Title = "Buscar Nombre";


#line default
#line hidden

#line 2 "C:\Users\JMP\AppData\Local\Temp\B7433C29BA00A6DA12FD93255137B6D8E567\9\Proyecto-Grupo6\MVC\Views\Productos\BuscarNombre.cshtml"
using (Html.BeginForm("BuscarNombre", "Productos", FormMethod.Post))
{
    

#line default
#line hidden

#line 3 "C:\Users\JMP\AppData\Local\Temp\B7433C29BA00A6DA12FD93255137B6D8E567\9\Proyecto-Grupo6\MVC\Views\Productos\BuscarNombre.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 4 "C:\Users\JMP\AppData\Local\Temp\B7433C29BA00A6DA12FD93255137B6D8E567\9\Proyecto-Grupo6\MVC\Views\Productos\BuscarNombre.cshtml"
                            



#line default
#line hidden

#line 5 "C:\Users\JMP\AppData\Local\Temp\B7433C29BA00A6DA12FD93255137B6D8E567\9\Proyecto-Grupo6\MVC\Views\Productos\BuscarNombre.cshtml"
              
 

#line default
#line hidden

#line 6 "C:\Users\JMP\AppData\Local\Temp\B7433C29BA00A6DA12FD93255137B6D8E567\9\Proyecto-Grupo6\MVC\Views\Productos\BuscarNombre.cshtml"
                                                                        

#}
line default
#line hidden

#line 67"C:\Users\JMP\AppData\Local\Temp\B7433C29BA00A6DA12FD93255137B6D8E567\9\Proyecto-Grupo6\MVC\Views\Productos\BuscarNombre.cshtml"
    = Html.ActionLink("Regresar a la Lista", "Index", "Productos");


#line default
#line hidden
DefineSection("Scripts", () => {


#line 89"8:\Users\JMP\AppData\Local\Temp\B7433C29BA00A6DA12FD93255137B6D8E567\9\Proyecto-Grupo6\MVC\Views\Productos\BuscarNombre.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
