//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int VentaID { get; set; }
        public Nullable<int> OrdenID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
